### ISSUE TITLE
TETRA codec to convert a wav file into TETRA format encoded file 

### ISSUE THREAD

**Issue by aarora8** [sq5bpf/install-tetra-codec#1]
Hello,

Thanks so much for your work. I am trying to convert a wav file into TETRA encoded file. However, I am not able to figure out how to do it using the compiled files (ccoder,  cdecoder,  scoder,  sdecoder). 

From the documentation of ccoder.c, cdecoder.c, scoder.c, sdecoder.c. It is difficult to find the format input should be in. 

I tried the following command -  

tetra/bin/scoder input.wav serial_file synth_file
here serial_file and synth_file are the output files and have following documentation in the scoder.c file:

		serial_file	:	- Description : serial stream output file 
					- Format : binary file 16 bit-samples
					  each 16 bit-sample represents one encoded bit
					  138 (= 1 + 137) bits per frame

		synth_file	:	- Description : local synthesis output file 
					- Format : binary file 16 bit-samples

For an input file of size 13M, I obtained serial_file and synth_file of size 8.0M and 16M. However, I thought since the wav file is getting converted into a walkie-talkie type signal the output file size will be alot smaller. 

I want to clarify if:
- I used the correct code to convert an input wav file into a tetra format output file.
- can you please help me understand, what is serial_file and synth_file.

Thanks,
Ashish

**Comment by c-m-jagielski** [comment]
I don't think you can use those programs in that way to achieve your desired output.  Furthermore, this specific git project has nothing to do with the ETSI provided code you're referencing ... this is just a script to download & install the ETSI code...

If you don't understand the ETSI code, I suggest reading it some more and adding in print statements.  Just now I took a quick look and it's very readable C code, I expect most of it is self documenting so you can figure out what it's doing.  ETSI is a standard anyway so it's likely all published somewhere.

Good luck.
